import { FadeIn } from "@/components/ui/fade-in"
import Link from "next/link"

export const metadata = {
 title: "Write For Us | Renewable Observer",
 description: "Share your expertise with the global clean energy industry. Pitch a guest article or opinion piece to Renewable Observer.",
}

export default function WriteForUsPage() {
 return (
 <div className="container mx-auto px-4 py-16 min-h-screen">
 <FadeIn>
 <div className="max-w-4xl mx-auto mb-12 text-center">
 <h1 className="text-4xl md:text-5xl font-bold tracking-tighter mb-4 text-primary">Write For Us</h1>
 <p className="text-lg text-muted-foreground font-medium">Share your expertise and build topical authority with our global audience</p>
 </div>
 </FadeIn>

 <div className="max-w-3xl mx-auto">
 <FadeIn delay={0.1}>
 <div className="prose prose-lg dark:prose-invert max-w-none text-muted-foreground space-y-8">
 <section>
 <p className="text-xl leading-relaxed mb-6 font-medium text-foreground">Renewable Observer is committed to elevating the voices of industry leaders, engineers, analysts, and sustainability advocates. If you have unique insights, deep technical knowledge, or a strong perspective on the clean energy transition, we want to hear from you.</p>
 </section>

 <section>
 <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Why Contribute?</h2>
 <p>Contributing an opinion editorial (Op-Ed), technical deep-dive, or market analysis to Renewable Observer offers significant benefits:</p>
 <ul className="list-disc pl-5">
 <li><strong>Reach Decision Makers:</strong> Your article will be read by executives, policymakers, and investors across the renewable energy ecosystem.</li>
 <li><strong>Build E-E-A-T:</strong> Establish your Experience, Expertise, Authoritativeness, and Trustworthiness in your specific niche.</li>
 <li><strong>Amplify Your Brand:</strong> Contributors receive an author bio with a link back to their professional profile or company website.</li>
 </ul>
 </section>

 <section className="bg-background border-y border-border p-8 border">
 <h2 className="text-2xl font-bold text-foreground mb-4">What We Look For</h2>
 <p>We are highly selective about the guest content we publish. Successful pitches usually fall into one of these categories:</p>
 <ul className="list-disc pl-5">
 <li><strong>Market Analysis:</strong> Data-driven insights on supply chains, pricing trends, or regional developments (e.g., "Why European Solar Manufacturing is Pivoting in 2026").</li>
 <li><strong>Technical Explainers:</strong> Deep-dives into emerging technologies authored by engineers or scientists (e.g., "Understanding the Degradation Rates of Solid-State Batteries").</li>
 <li><strong>Policy Perspectives:</strong> Op-Eds from legal or policy experts on regulatory impacts (e.g., "How the New Grid Interconnection Rules Affect Wind Developers").</li>
 <li><strong>Leadership & Strategy:</strong> C-suite perspectives on scaling renewable businesses or managing ESG compliance.</li>
 </ul>
 <p className="font-semibold text-foreground mt-4">Note: We do NOT accept overtly promotional posts, generic introductory articles ("What is Solar Energy?"), or articles generated by AI.</p>
 </section>

 <section>
 <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Submission Guidelines</h2>
 <ol className="list-decimal pl-5 space-y-3">
 <li><strong>Pitch First:</strong> Please do not send a completed manuscript. Send a brief pitch (2-3 paragraphs) outlining your core argument, why it matters right now, and why you are the right person to write it.</li>
 <li><strong>Length:</strong> If approved, final articles should be between 800 and 1,500 words.</li>
 <li><strong>Originality:</strong> Submissions must be 100% original and not published elsewhere (including on your own corporate blog or LinkedIn).</li>
 <li><strong>Evidence-Based:</strong> Claims and data points must be supported with links to authoritative sources.</li>
 </ol>
 </section>

 <section className="bg-background border-t-4 border-t-primary border-x border-b border-border border border-primary/20 p-8 text-center md:text-left mt-12">
 <h2 className="text-2xl font-bold text-foreground mb-4">How to Pitch</h2>
 <p className="text-muted-foreground mb-6">Send your pitch and a brief bio (or LinkedIn link) to our editorial team:</p>
 <div>
 <strong className="block text-sm uppercase tracking-wider text-muted-foreground mb-1">Editorial Desk</strong>
 <a href="mailto:editor@renewableobserver.com" className="text-xl font-bold text-secondary hover:underline">editor@renewableobserver.com</a>
 </div>
 <p className="mt-4 text-sm">Please use the subject line: <strong>GUEST PITCH: [Proposed Headline]</strong></p>
 <p className="mt-6 text-sm text-muted-foreground">Due to high email volume, we will only respond to pitches that are a strong fit for our editorial calendar. If you do not hear back within 7 days, feel free to pitch your idea elsewhere.</p>
 </section>
 </div>
 </FadeIn>
 </div>
 </div>
 )
}
